AY2122S1-CS2113T-T10-1/tp

src/main/java/command/CommandSyntax.java
src/main/java/command/medicine/DeleteCommand.java
src/main/java/inventory/Medicine.java
src/main/java/parser/MedicineValidator.java
src/main/java/parser/Parser.java

Implemented deletion of medication stock based on stockId
Updated MedicineValidator.isValidStockId as well to handle more edge cases
Fixes #16

Add delete feature

---

src/main/java/command/CommandParameters.java
src/main/java/command/CommandSyntax.java
src/main/java/command/medicine/UpdateCommand.java
src/main/java/parser/Parser.java

Implemented update command with stock id provided by user
Fix #15

Implement update command

---

src/main/java/MediVault.java
src/main/java/command/CommandSyntax.java
src/main/java/command/medicine/AddCommand.java
src/main/java/command/medicine/DeleteCommand.java
src/main/java/command/medicine/UpdateCommand.java
src/main/java/parser/MedicineManager.java
src/main/java/parser/StockValidator.java

Modified invalid parameter and parameter value checker to check for both required and optional parameters 
Fix #30 
Implemented validity checker for quantity and expiry date
Fix #31 
Fix #39
Modified update command to use newly implemented methods
Modified update command logic to update all affected rows
Fix #32

Modify update command logic

---

src/test/java/parser/StockValidatorTest.java

Add JUnit test

---

src/test/java/parser/StockValidatorTest.java

Implement JUnit test for expiry date

---

src/main/java/command/CommandSyntax.java
src/main/java/command/medicine/AddCommand.java
src/main/java/command/medicine/DeleteCommand.java
src/main/java/command/medicine/ListCommand.java
src/main/java/command/medicine/UpdateCommand.java

Modify containsInvalidParameters

---

src/main/java/MediVault.java
src/main/java/command/medicine/ListCommand.java
src/main/java/inventory/Dispense.java
src/main/java/inventory/Order.java
src/main/java/inventory/Stock.java
src/main/java/parser/Parser.java
src/main/java/ui/Ui.java

Add print table for order and dispense

---

src/main/java/command/medicine/ListCommand.java

Modify list command by name and description

---

src/main/java/command/CommandParameters.java
src/main/java/command/CommandSyntax.java
src/main/java/command/medicine/UpdateCommand.java
src/main/java/parser/MedicineManager.java

Fix #44 
Fix #43 
Fix #60 
Added assertions and loggings

Modify update command

---

build.gradle
src/main/java/command/medicine/DeleteCommand.java

Improve defensiveness of delete command through assertions and logging

---

src/main/java/ui/Ui.java
src/test/java/parser/ParserTest.java

Add JUnit test for parser

---

src/main/java/command/medicine/ListCommand.java
src/main/java/parser/MedicineManager.java
src/main/java/ui/Ui.java

Add ordered quantity in table

---

src/main/java/command/CommandParameters.java
src/main/java/command/CommandSyntax.java
src/main/java/command/HelpCommand.java
src/main/java/command/dispense/ListDispense.java
src/main/java/comparators/DispenseComparator.java
src/main/java/inventory/Dispense.java
src/main/java/parser/DispenseValidator.java
src/main/java/parser/MedicineManager.java
src/main/java/parser/Parser.java
src/main/java/parser/StockValidator.java
src/main/java/ui/Ui.java

Add listdispense

---

src/main/java/MediVault.java
src/main/java/command/Command.java
src/main/java/command/CommandList.java
src/main/java/command/CommandParameters.java
src/main/java/command/CommandSyntax.java
src/main/java/command/ExitCommand.java
src/main/java/command/HelpCommand.java
src/main/java/command/PurgeCommand.java
src/main/java/command/dispense/AddDispense.java
src/main/java/command/dispense/ListDispense.java
src/main/java/command/medicine/AddStock.java
src/main/java/command/medicine/DeleteStock.java
src/main/java/command/medicine/ListStock.java
src/main/java/command/medicine/UpdateStock.java
src/main/java/command/order/DeleteOrder.java
src/main/java/command/order/ListOrder.java
src/main/java/command/order/UpdateOrder.java
src/main/java/comparators/DispenseComparator.java
src/main/java/parser/CommandParser.java
src/main/java/parser/DispenseValidator.java
src/main/java/parser/MedicineManager.java
src/main/java/parser/Mode.java
src/main/java/parser/OrderManager.java
src/main/java/parser/OrderValidator.java
src/main/java/parser/StockValidator.java
src/main/java/ui/Ui.java
src/test/java/parser/CommandParserTest.java

Add mode feature and refactor HashMap to LinkedHashMap

---

src/main/java/command/dispense/AddDispense.java
src/main/java/command/medicine/AddStock.java

Improve dispense and addstock command

---

config/checkstyle/checkstyle.xml
src/main/java/MediVault.java
src/main/java/command/dispense/ListDispense.java
src/main/java/parser/Mode.java
src/main/java/ui/Ui.java

Fix array initialisation error.

---

src/main/java/command/CommandParameters.java
src/main/java/command/CommandSyntax.java
src/main/java/command/order/DeleteOrderCommand.java
src/test/java/parser/OrderValidatorTest.java

Change order id parameter from oid to i

Modify orderId parameter

---

docs/diagrams/MainLogicSequenceDiagram.puml
src/main/java/command/CommandSyntax.java
src/main/java/command/dispense/AddDispenseCommand.java
src/main/java/command/dispense/DeleteDispenseCommand.java
src/main/java/command/order/AddOrderCommand.java
src/main/java/command/order/ListOrderCommand.java
src/main/java/inventory/Dispense.java
src/main/java/inventory/Order.java
src/main/java/utilities/comparators/DispenseComparator.java
src/main/java/utilities/comparators/OrderComparator.java
src/main/java/utilities/parser/CommandParser.java
src/main/java/utilities/parser/DispenseValidator.java
src/main/java/utilities/parser/MedicineValidator.java
src/main/java/utilities/parser/OrderValidator.java
src/main/java/utilities/parser/StockValidator.java

Implement sort for list order

---

docs/DeveloperGuide.md
src/main/java/command/order/ReceiveOrderCommand.java
src/main/java/command/stock/AddStockCommand.java
src/main/java/utilities/parser/StockManager.java

Fix bug in addstock and receiveorder. Update DG

---

docs/DeveloperGuide.md
src/main/java/command/prescription/AddPrescriptionCommand.java

Add instruction for manual testing in DG. Fix bug in addprescription

---

docs/DeveloperGuide.md

Add Value Proposition and NFR into DG

---

docs/UserGuide.md
docs/team/alvintan01.md
src/main/java/command/CommandSyntax.java
src/main/java/utilities/parser/MedicineValidator.java
src/main/java/utilities/ui/Ui.java

Fix: #240
Fix: #245 
Fix: #246 
Fix: #250 
Fix: #251 
Fix: #253 
Fix: #263

Update PPP, fix bugs and add missing details to UG

---

docs/DeveloperGuide.md
src/main/java/command/order/ArchiveOrderCommand.java
src/main/java/command/prescription/ArchivePrescriptionCommand.java
src/main/java/utilities/storage/Storage.java

Added javadocs for archive commands
Improve code quality to remove magic literal and unnecessary comments. Fix #237 
Add more explanation into DG

Improve code quality and update DG

---

src/main/java/command/order/AddOrderCommand.java
src/test/java/command/order/AddOrderCommandTest.java
src/test/java/command/stock/ListStockCommandTest.java

Add Junit tests for ListStockCommand and AddOrderCommand
